# generated by chatGPT
import re
from flask import Flask, render_template, request, jsonify, flash
import sys
import corpus_b

app = Flask(__name__)
app.secret_key = 'kwic_analyzer_secret_key'

@app.route('/', methods=['GET', 'POST'])
def index():
    results = None
    wiki_topic = ""
    search_words = ""
    window = 5
    color = "red" 
    error_message = ""
    
    try:
        if request.method == 'POST':
            wiki_topic = request.form.get('wiki_topic', '')
            search_words = request.form.get('search_words', '')
            window = int(request.form.get('window', 5))
            color = request.form.get('color', 'red')
            
            if not wiki_topic.strip():
                error_message = "Please enter a Wikipedia topic."
                return render_template('index.html', 
                                      results=None, 
                                      wiki_topic="",
                                      search_words=search_words,
                                      window=window,
                                      color=color,
                                      error_message=error_message)
            
            if not search_words.strip():
                error_message = "Please enter a search term."
                return render_template('index.html', 
                                      results=None, 
                                      wiki_topic=wiki_topic,
                                      search_words="",
                                      window=window,
                                      color=color,
                                      error_message=error_message)
            
            corpus_b.text = ""
            corpus_b.text += corpus_b.add_wikipedia_article(wiki_topic)
            
            if corpus_b.text.strip():
                import io
                from contextlib import redirect_stdout
                
                f = io.StringIO()
                with redirect_stdout(f):
                    corpus_b.kwic_grouped_by_pos_and_sorted(corpus_b.text, search_words, window=window, color=color)
                
                output = f.getvalue()
                
                if output.strip():
                    categories = []
                    current_category = None
                    current_lines = []
                    
                    for line in output.split('\n'):
                        if line.startswith('<') and line.endswith('>'):
                            if current_category:
                                categories.append({
                                    'name': current_category,
                                    'lines': current_lines
                                })
                            current_category = line.strip('<>')
                            current_lines = []
                        elif line.strip() and current_category:
                            color_code_map = {
                                'red': '\033[91m',
                                'green': '\033[92m',
                                'yellow': '\033[93m',
                                'blue': '\033[94m',
                                'magenta': '\033[95m',
                                'cyan': '\033[96m'
                            }
                            
                            color_code = color_code_map.get(color, '\033[91m')
                            end_code = '\033[0m'
                            
                            line = line.replace(color_code, '<span class="highlight ' + color + '">').replace(end_code, '</span>')
                            current_lines.append(line)
                    
                    if current_category and current_lines:
                        categories.append({
                            'name': current_category,
                            'lines': current_lines
                        })
                    
                    results = categories
                else:
                    error_message = f"No matches found for '{search_words}'. Please try a different search term."
            else:
                error_message = f"Could not find Wikipedia article for '{wiki_topic}'. Please try a different topic."
                results = []
    except Exception as e:
        error_message = f"An error occurred: {str(e)}"
        print(f"Error in processing request: {e}")
    
    return render_template('index.html', 
                          results=results, 
                          wiki_topic=wiki_topic,
                          search_words=search_words,
                          window=window,
                          color=color,
                          error_message=error_message)

@app.route('/api/kwic', methods=['POST'])
def kwic_api():
    try:
        data = request.get_json()
        wiki_topic = data.get('wiki_topic', '')
        search_words = data.get('search_words', '')
        window = int(data.get('window', 5))
        color = data.get('color', 'red')
        
        if not wiki_topic.strip():
            return jsonify({"success": False, "error": "Please enter a Wikipedia topic."})
        
        if not search_words.strip():
            return jsonify({"success": False, "error": "Please enter a search term."})
        
        corpus_b.text = ""
        corpus_b.text += corpus_b.add_wikipedia_article(wiki_topic)
        
        if corpus_b.text.strip():
            import io
            from contextlib import redirect_stdout
            
            f = io.StringIO()
            with redirect_stdout(f):
                corpus_b.kwic_grouped_by_pos_and_sorted(corpus_b.text, search_words, window=window, color=color)
            
            output = f.getvalue()
            
            if output.strip():
                categories = []
                current_category = None
                current_lines = []
                
                for line in output.split('\n'):
                    if line.startswith('<') and line.endswith('>'):
                        if current_category:
                            categories.append({
                                'name': current_category,
                                'lines': current_lines
                            })
                        current_category = line.strip('<>')
                        current_lines = []
                    elif line.strip() and current_category:
                        color_code_map = {
                            'red': '\033[91m',
                            'green': '\033[92m',
                            'yellow': '\033[93m',
                            'blue': '\033[94m',
                            'magenta': '\033[95m',
                            'cyan': '\033[96m'
                        }
                        
                        color_code = color_code_map.get(color, '\033[91m')
                        end_code = '\033[0m'
                        
                        line = line.replace(color_code, '<span class="highlight ' + color + '">').replace(end_code, '</span>')
                        current_lines.append(line)
                
                if current_category and current_lines:
                    categories.append({
                        'name': current_category,
                        'lines': current_lines
                    })
                
                return jsonify({"success": True, "results": categories})
            else:
                return jsonify({"success": False, "error": f"No matches found for '{search_words}'. Please try a different search term."})
        else:
            return jsonify({"success": False, "error": f"Could not find Wikipedia article for '{wiki_topic}'. Please try a different topic."})
    except Exception as e:
        return jsonify({"success": False, "error": f"An error occurred: {str(e)}"})

if __name__ == '__main__':
    app.run(debug=True) 